[tool.poetry]
name = "stock-prices"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"
packages = [{include = "stock_prices"}]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
